description: Thanks for pinging me.
# Theme
theme: jekyll-theme-cayman
# Google Analytics
google_analytics: UA-114243378-1
# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-redirect-to
# SEO Tag
twitter:
  username: soarnpro
  card: summary
logo: /favicon.ico
image: /icons/favicon-194x194.png